### ISSUE TITLE
Version 0.0.13 Checklist

### ISSUE THREAD

**Issue by psion** [SeleneSoftware/seleneCMSBundle#33]
These features are a must-have to release version 0.0.13

- [ ] Navbar and Footer links editor
- [ ] Need to have a method to add CRUD controllers and menus to the dashboard
- [ ] Foundation for plugins
- [ ] better theming via composer
